name: HuLC
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  # Core Python & Data Science
  - python=3.11.11
  - pip=25.0
  - numpy=1.23.5
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - jupyter=1.1.1
  - jupyterlab=4.3.4
  - ipykernel=6.29.5

  # Other ML/NLP tools
  - keras=3.6.0
  - h5py=3.12.1
  - pillow=11.1.0
  - opencv=4.10.0
  - tesseract=5.3.3
  - pytesseract=0.3.10
  - nltk=3.8.1
  - spacy=3.7.4
  - transformers=4.40.1

  # Pip packages (for DirectML)
  - pip:
    - tensorflow-directml-plugin==2.15.0  # Installs DirectML version of TensorFlow
    - image-classifiers==1.0.0
    - keras-applications==1.0.8
    - protobuf==3.20.3  # Avoid conflicts with TensorFlow